---

- hosts: all
  ignore_errors: yes
  become: yes
  tasks:
  - name: create user
    user:
      name: christelle
      comment: christelle Tikaya
  - name: create directory
    file:
      path: /tmp/devops-ans
      owner: christelle
      state: directory
      mode: "0777"
  - name: create file
    file:
      path: /tmp/ansible-class
      owner: christelle
      state: touch  
      mode: "0600"
